"use client";
import { FormEvent,useState } from "react";
type Expert={name:string;institution:string;area:string;topics:string[];match:number;why:string;email:string;updated:string};
const experts:Record<string,Expert[]>={
  desinformacao:[{name:"Ana Ribeiro",institution:"Universidade Federal Demonstrativa",area:"Comunicação e política",topics:["desinformação","plataformas digitais","eleições"],match:96,why:"Pesquisa diretamente circulação de conteúdo enganoso e moderação de plataformas.",email:"ana.ribeiro@universidade-exemplo.invalid",updated:"15 jul. 2026"},{name:"João Mendonça",institution:"Universidade Estadual de Exemplo",area:"Ciência da computação",topics:["detecção automática","redes sociais","IA responsável"],match:88,why:"Atua em métodos computacionais para identificar padrões de propagação.",email:"joao.mendonca@universidade-exemplo.invalid",updated:"8 jul. 2026"},{name:"Lívia Santos",institution:"Instituto Público Fictício",area:"Saúde coletiva",topics:["desinformação em saúde","vacinas","comunicação de risco"],match:81,why:"Especialização adequada quando a pauta envolve saúde pública.",email:"livia.santos@instituto-exemplo.invalid",updated:"30 jun. 2026"}],
  clima:[{name:"Carlos Azevedo",institution:"Universidade Federal Demonstrativa",area:"Climatologia",topics:["eventos extremos","mudança climática","modelagem"],match:94,why:"Aderência direta a eventos extremos e comunicação de incerteza climática.",email:"carlos.azevedo@universidade-exemplo.invalid",updated:"17 jul. 2026"},{name:"Beatriz Lima",institution:"Universidade Estadual de Exemplo",area:"Planejamento urbano",topics:["adaptação","risco urbano","políticas públicas"],match:84,why:"Pode contextualizar impactos e respostas de cidades a extremos.",email:"beatriz.lima@universidade-exemplo.invalid",updated:"2 jul. 2026"}],
  inteligencia:[{name:"João Mendonça",institution:"Universidade Estadual de Exemplo",area:"Ciência da computação",topics:["inteligência artificial","auditoria algorítmica","IA responsável"],match:95,why:"Pesquisa avaliação e governança de sistemas algorítmicos.",email:"joao.mendonca@universidade-exemplo.invalid",updated:"8 jul. 2026"},{name:"Renata Freire",institution:"Universidade Pública Piloto",area:"Direito digital",topics:["regulação de IA","direitos digitais","proteção de dados"],match:86,why:"Contribui com perspectiva regulatória e de direitos.",email:"renata.freire@universidade-exemplo.invalid",updated:"12 jul. 2026"}]
};
function category(q:string){const s=q.toLowerCase();if(s.includes("clima")||s.includes("enchente"))return "clima";if(s.includes("ia")||s.includes("inteligência")||s.includes("algorit"))return "inteligencia";return "desinformacao"}
export default function Home(){const [query,setQuery]=useState("quem pesquisa desinformação?");const [sent,setSent]=useState("quem pesquisa desinformação?");const [loading,setLoading]=useState(false);const [detail,setDetail]=useState<Expert|null>(null);const [empty,setEmpty]=useState(false);const results=experts[category(sent)];function submit(e:FormEvent){e.preventDefault();setLoading(true);setTimeout(()=>{setSent(query);setEmpty(query.trim().length<5||query.toLowerCase().includes("oceanografia lunar"));setLoading(false)},650)}return <main>
  <div className="demo"><b>SIMULAÇÃO PÚBLICA</b><span>Nomes, instituições e contatos são fictícios. Este site demonstra a experiência futura do bot no Slack.</span></div>
  <header><a href="#" className="brand"><span>F</span><div><b>Fonte Certa</b><small>bot de especialistas</small></div></a><div className="status"><i/> protótipo online</div></header>
  <section className="hero"><div><p className="eyebrow">FONTES ACADÊMICAS PARA JORNALISTAS</p><h1>Uma pergunta.<br/><em>Boas fontes para começar.</em></h1><p>Veja como o bot poderá localizar docentes de universidades públicas a partir do tema de uma pauta.</p><div className="coverage"><span>LOTE-PILOTO SIMULADO</span><b>3 instituições · 6 perfis de exemplo</b></div></div><div className="slack-mini"><div className="slack-top"><span>● ● ●</span><b># pauta-do-dia</b></div><div className="mini-message"><i>PB</i><p><b>Pedro</b><span>10:42</span><br/>@FonteCerta quem pesquisa desinformação?</p></div><div className="mini-message bot"><i>F</i><p><b>Fonte Certa <em>APP</em></b><span>10:42</span><br/>Encontrei 3 fontes no lote-piloto. Veja por que cada perfil pode ajudar ↓</p></div></div></section>
  <section className="simulator"><div className="sim-head"><p className="eyebrow">TESTE A CONSULTA</p><h2>Simulador do bot</h2><p>Experimente desinformação, mudança climática ou inteligência artificial.</p></div><div className="slack-window"><div className="channel-head"><div><b># pesquisa-de-fontes</b><span>Canal demonstrativo</span></div><span>⌕ ⓘ</span></div><div className="messages"><div className="message user"><div className="avatar">PB</div><div><b>Jornalista <small>agora</small></b><p><strong>@FonteCerta</strong> {sent}</p></div></div>{loading?<div className="typing"><i/><i/><i/> Buscando no lote demonstrativo…</div>:empty?<div className="message bot-message"><div className="bot-avatar">F</div><div><b>Fonte Certa <em>APP</em></b><p>Não encontrei correspondências no lote-piloto. Tente descrever o tema com outras palavras ou mencionar uma área de conhecimento.</p><button onClick={()=>{setQuery("quem pesquisa inteligência artificial responsável?");setEmpty(false)}}>Usar uma sugestão</button></div></div>:<div className="message bot-message"><div className="bot-avatar">F</div><div className="bot-content"><b>Fonte Certa <em>APP</em></b><p>Encontrei {results.length} perfis relacionados no <strong>lote simulado</strong>. Confira a origem antes de contatar uma fonte.</p><div className="expert-list">{results.map((e,i)=><button key={e.name} onClick={()=>setDetail(e)}><span className="order">{i+1}</span><div><b>{e.name}</b><small>{e.institution} · {e.area}</small><p>{e.why}</p><div className="tags">{e.topics.slice(0,3).map(t=><i key={t}>{t}</i>)}</div></div><strong className="match">{e.match}%<small>aderência</small></strong></button>)}</div><p className="disclaimer">⚠ Dados fictícios para demonstração. A versão real mostrará somente páginas oficiais verificáveis.</p></div></div>}</div><form onSubmit={submit}><button type="button" className="plus">＋</button><div><span>@FonteCerta</span><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Pergunta ao bot"/></div><button className="send" disabled={loading}>↑</button></form><div className="suggestions"><span>Testar:</span>{["quem pesquisa mudança climática?","fontes sobre inteligência artificial responsável","especialistas em desinformação em saúde"].map(q=><button key={q} onClick={()=>{setQuery(q);setSent(q);setEmpty(false)}}>{q}</button>)}</div></div></section>
  <section className="how"><div><p className="eyebrow">COMO FUNCIONARÁ</p><h2>Da página institucional<br/>à resposta no Slack.</h2></div><ol><li><span>01</span><b>Coleta responsável</b><p>Somente páginas oficiais e contatos profissionais publicados.</p></li><li><span>02</span><b>Busca por tema</b><p>Correspondência por área e especialidades, com lote coberto visível.</p></li><li><span>03</span><b>Conferência humana</b><p>O jornalista abre a origem e faz o contato fora do sistema.</p></li></ol></section>
  <footer><b>Fonte Certa · Grupo 3</b><span>Próxima etapa: bot privado no Slack e base nacional verificada</span></footer>
  {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><article className="modal" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button className="close" onClick={()=>setDetail(null)}>×</button><span className="fake-label">PERFIL FICTÍCIO · DEMONSTRAÇÃO</span><h2>{detail.name}</h2><p>{detail.institution}<br/>{detail.area}</p><h3>Por que apareceu</h3><p>{detail.why}</p><h3>Temas</h3><div className="tags">{detail.topics.map(t=><i key={t}>{t}</i>)}</div><dl><div><dt>Contato profissional simulado</dt><dd>{detail.email}</dd></div><div><dt>Última atualização fictícia</dt><dd>{detail.updated}</dd></div><div><dt>Página institucional</dt><dd>Indisponível — registro demonstrativo</dd></div></dl><div className="warning"><b>Não use este contato</b><p>O domínio .invalid confirma que este registro não pertence a uma pessoa real.</p></div></article></div>}
  </main>}
