import type { Curator, Expert, University } from "@/lib/types";

const SEEDED_AT = "2026-08-17T12:00:00.000Z";
const VERIFIED_AT = "2026-08-17";

export const seedUniversities: University[] = [
  {
    id: "ufmg",
    name: "Universidade Federal de Minas Gerais",
    acronym: "UFMG",
    state: "MG",
    directoryUrl: "https://somos.ufmg.br/",
    directoryLabel: "Somos UFMG",
    notes: "Diretório institucional central e pesquisável, com perfis e produção acadêmica.",
    isActive: true,
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
  },
  {
    id: "unicamp",
    name: "Universidade Estadual de Campinas",
    acronym: "Unicamp",
    state: "SP",
    directoryUrl: "https://portal.dados.unicamp.br/",
    directoryLabel: "Portal Dados Unicamp",
    notes: "Portal institucional central com busca por docentes, temas, unidades e programas.",
    isActive: true,
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
  },
  {
    id: "usp",
    name: "Universidade de São Paulo",
    acronym: "USP",
    state: "SP",
    directoryUrl: "https://www5.usp.br/keywords-s/pesquisadores-usp/",
    directoryLabel: "Pesquisadores USP e diretórios das unidades",
    notes: "Perfis públicos oficiais distribuídos entre portais de unidades, institutos e serviços USP.",
    isActive: true,
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
  },
];

type SeedExpert = Omit<Expert, "universityName" | "universityAcronym">;
type SeedExpertInput = Omit<
  SeedExpert,
  "email" | "phone" | "status" | "createdAt" | "updatedAt" | "updatedBy"
>;

function expert(input: SeedExpertInput): SeedExpert {
  return {
    ...input,
    email: null,
    phone: null,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-tematica-30",
  };
}

export const seedExperts: SeedExpert[] = [
  expert({
    id: "ufmg-fabricio-benevenuto",
    universityId: "ufmg",
    name: "Fabrício Benevenuto de Souza",
    title: "Professor associado",
    department: "Departamento de Ciência da Computação",
    area: "Computação social e desinformação",
    specialties: ["checagem de informação", "desinformação eleitoral", "WhatsApp", "redes sociais", "viralização"],
    summary: "Cientista da computação que coordena projetos de monitoramento da circulação de desinformação em redes sociais e aplicativos de mensagem. Pode ajudar a rastrear origem, alcance e padrões de viralização de conteúdos eleitorais.",
    profileUrl: "https://dcc.ufmg.br/professor/fabricio-benevenuto-de-souza/",
    sourceLabel: "Departamento de Ciência da Computação da UFMG",
    referenceTitle: "Universidades e fake news: estudiosos analisam fenômeno",
    referenceUrl: "https://www3.ufmg.br/comunicacao/noticias/universidades-e-fake-news-pesquisadores-analisam-fenomeno",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "ufmg-marcus-abilio-pereira",
    universityId: "ufmg",
    name: "Marcus Abílio Gomes Pereira",
    title: "Professor associado",
    department: "Departamento de Ciência Política",
    area: "Democracia digital e participação política",
    specialties: ["fake news", "democracia digital", "participação política", "comportamento político", "confiança institucional"],
    summary: "Cientista político que estuda participação, democracia digital e os efeitos sociais da circulação de informação. Pode contextualizar como fake news se conectam a comportamento político, mobilização e confiança nas instituições.",
    profileUrl: "https://ppgcp.fafich.ufmg.br/corpodocdet.php?numaut=17&origem=linha",
    sourceLabel: "Programa de Pós-Graduação em Ciência Política da UFMG",
    referenceTitle: "Universidades e fake news: estudiosos analisam fenômeno",
    referenceUrl: "https://www3.ufmg.br/comunicacao/noticias/universidades-e-fake-news-pesquisadores-analisam-fenomeno",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "ufmg-carlos-dandrea",
    universityId: "ufmg",
    name: "Carlos Frederico de Brito D'Andréa",
    title: "Professor",
    department: "Departamento de Comunicação Social",
    area: "Plataformas digitais e desordem informacional",
    specialties: ["desinformação", "plataformas digitais", "mídias sociais", "métodos digitais", "controvérsias"],
    summary: "Pesquisador de comunicação digital que analisa controvérsias, plataformas e ecossistemas de desinformação. Pode ajudar a entender quem financia, distribui e amplifica narrativas enganosas — e como investigá-las sem olhar apenas para uma postagem isolada.",
    profileUrl: "https://somos.ufmg.br/professor/Carlos-Frederico-de-Brito-D-Andrea",
    sourceLabel: "Somos UFMG",
    referenceTitle: "O caos informacional tem financiadores e lobistas especializados em implantar dúvidas",
    referenceUrl: "https://www3.ufmg.br/comunicacao/noticias/o-caos-informacional-tem-financiadores-e-lobistas-especializados-em-implantar-duvidas",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "ufmg-lorena-tavares",
    universityId: "ufmg",
    name: "Lorena Tavares de Paula",
    title: "Professora",
    department: "Escola de Ciência da Informação",
    area: "Fontes de informação e pós-verdade",
    specialties: ["checagem de fake news", "fontes de informação", "pós-verdade", "curadoria digital", "cultura informacional"],
    summary: "Coordenadora do Observatório Fake News, pesquisa métodos para avaliar autoria, contexto, institucionalidade e qualidade de fontes. É uma fonte especialmente útil para desenhar rotinas de checagem e distinguir notícia, sátira, impostura e conteúdo enganoso.",
    profileUrl: "https://somos.ufmg.br/professor/lorena-tavares-de-paula",
    sourceLabel: "Somos UFMG",
    referenceTitle: "O bibliotecário no combate às fake news é destaque na UFMG",
    referenceUrl: "https://www.bu.ufmg.br/bu_atual/noticias/o-bibliotecario-no-combate-as-fake-news-e-destaque-da-quarta-semana-do-bibliotecario-da-eci/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "ufmg-yurij-castelfranchi",
    universityId: "ufmg",
    name: "Yurij Castelfranchi",
    title: "Professor associado",
    department: "Departamento de Sociologia",
    area: "Comunicação pública da ciência",
    specialties: ["fake news", "crenças", "negacionismo", "comunicação científica", "percepção pública da ciência"],
    summary: "Sociólogo da ciência que pesquisa como valores, identidades e escolhas políticas moldam a aceitação de informações. Pode explicar por que corrigir um dado falso nem sempre muda uma crença e como comunicar evidências em temas polarizados.",
    profileUrl: "https://somos.ufmg.br/professor/juri-castelfranchi",
    sourceLabel: "Somos UFMG",
    referenceTitle: "Yurij Castelfranchi: fake news sustentam escolhas políticas",
    referenceUrl: "https://www3.ufmg.br/comunicacao/noticias/yurij-castelfranchi-fake-news-sustentam-escolhas-politicas",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "ufmg-ernesto-perini-santos",
    universityId: "ufmg",
    name: "Ernesto Perini-Santos",
    title: "Professor",
    department: "Departamento de Filosofia",
    area: "Epistemologia social da desinformação",
    specialties: ["desinformação", "epistemologia", "teorias da conspiração", "negacionismo", "crença"],
    summary: "Filósofo que investiga as raízes conceituais e políticas da desinformação, do negacionismo e das teorias da conspiração. Pode ajudar a separar erro, crença injustificada e manipulação deliberada ao analisar uma alegação.",
    profileUrl: "https://somos.ufmg.br/professor/ernesto-perini-frizzera-da-mota-santos",
    sourceLabel: "Somos UFMG",
    referenceTitle: "Livro de professor da UFMG investiga raízes conceituais e políticas da desinformação",
    referenceUrl: "https://www.ufmg.br/comunicacao/assessoria-de-imprensa/releases/pesquisa-e-inovacao/livro-de-professor-da-ufmg-investiga-raizes-conceituais-e-politicas-da-desinformacao/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "ufmg-abilio-rodrigues",
    universityId: "ufmg",
    name: "Abilio Azambuja Rodrigues Filho",
    title: "Professor associado",
    department: "Departamento de Filosofia",
    area: "Lógica, evidência e argumentação",
    specialties: ["evidência", "justificação", "desinformação", "negacionismo", "lógica"],
    summary: "Filósofo da lógica que estuda evidência, justificação e argumentos em contextos de informação contraditória. Pode ajudar a testar se as premissas de uma alegação realmente sustentam a conclusão e a reconhecer pseudojustificativas.",
    profileUrl: "https://somos.ufmg.br/professor/abilio-azambuja-rodrigues-filho",
    sourceLabel: "Somos UFMG",
    referenceTitle: "Lógica e argumentação no contexto da desinformação",
    referenceUrl: "https://www.ufmg.br/comunicacao/eventos/evento-academico/ciclo-de-palestras-retorica-em-acao-recebe-o-professor-abilio-rodrigues/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "ufmg-camilo-aggio",
    universityId: "ufmg",
    name: "Camilo de Oliveira Aggio",
    title: "Professor",
    department: "Departamento de Comunicação Social",
    area: "Comunicação política digital",
    specialties: ["desinformação política", "regulação de plataformas", "campanhas eleitorais", "boatos", "mídias sociais"],
    summary: "Pesquisador de comunicação política e campanhas digitais, com atenção a boatos, plataformas e eleições. Pode contextualizar a responsabilidade das empresas de tecnologia e os limites de moderação e regulação de conteúdo.",
    profileUrl: "https://somos.ufmg.br/professor/camilo-de-oliveira-aggio",
    sourceLabel: "Somos UFMG",
    referenceTitle: "Plataformas digitais fazem pouco para coibir a desinformação, segundo especialistas",
    referenceUrl: "https://www3.ufmg.br/comunicacao/noticias/plataformas-digitais-fazem-pouco-para-coibir-a-desinformacao-segundo-especialistas",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "ufmg-virgilio-almeida",
    universityId: "ufmg",
    name: "Virgilio Augusto Fernandes Almeida",
    title: "Professor emérito",
    department: "Departamento de Ciência da Computação",
    area: "Governança da internet e inteligência artificial",
    specialties: ["desinformação sistêmica", "governança de plataformas", "inteligência artificial", "internet", "políticas digitais"],
    summary: "Cientista da computação especializado em governança da internet e inteligência artificial. Pode analisar desinformação como problema de arquitetura e incentivos das plataformas, além dos riscos de manipulação eleitoral em larga escala.",
    profileUrl: "https://dcc.ufmg.br/professor/virgilio-augusto-fernandes-almeida/",
    sourceLabel: "Departamento de Ciência da Computação da UFMG",
    referenceTitle: "Leonardo Sakamoto: em 2022, ainda teremos eleições manipuladas",
    referenceUrl: "https://www3.ufmg.br/comunicacao/noticias/leonardo-sakamoto-em-2022-ainda-teremos-eleicoes-manipuladas",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "ufmg-geane-alzamora",
    universityId: "ufmg",
    name: "Geane Carvalho Alzamora",
    title: "Professora",
    department: "Departamento de Comunicação Social",
    area: "Semiótica e circulação da desinformação",
    specialties: ["desinformação", "educomunicação", "semiótica", "conexões digitais", "crenças"],
    summary: "Pesquisadora de comunicação e semiótica que estuda como crenças e sentidos circulam em conexões digitais. Pode ajudar a reconhecer enquadramentos, escolhas de linguagem e estratégias narrativas que tornam uma falsidade persuasiva.",
    profileUrl: "https://somos.ufmg.br/professor/geane-carvalho-alzamora",
    sourceLabel: "Somos UFMG",
    referenceTitle: "Desinformação precisa ser combatida com escolhas responsáveis",
    referenceUrl: "https://www.ufmg.br/defesademocracia/noticia/desinformacao-precisa-ser-combatida-com-escolhas-responsaveis-afirma-geane-alzamora/",
    verifiedAt: VERIFIED_AT,
  }),

  expert({
    id: "unicamp-leda-gitahy",
    universityId: "unicamp",
    name: "Leda Maria Caira Gitahy",
    title: "Professora sênior",
    department: "Departamento de Política Científica e Tecnológica",
    area: "Economia política da desinformação",
    specialties: ["ecossistema da desinformação", "redes políticas", "financiamento", "tecnologia e sociedade", "organizações"],
    summary: "Pesquisadora de tecnologia e sociedade que mapeia atores, organizações e relações econômicas no ecossistema da desinformação. Pode ajudar a investigar a infraestrutura política e financeira por trás de campanhas coordenadas.",
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=109835&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    referenceTitle: "O ecossistema da desinformação",
    referenceUrl: "https://unicamp.br/unicamp/noticias/2020/08/20/o-ecossistema-da-desinformacao",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "unicamp-leandro-tessler",
    universityId: "unicamp",
    name: "Leandro Russovski Tessler",
    title: "Professor associado",
    department: "Instituto de Física Gleb Wataghin",
    area: "Rastreamento de desinformação científica",
    specialties: ["fake news", "checagem científica", "redes sociais", "covid-19", "evolução de narrativas"],
    summary: "Físico e coordenador de iniciativas que acompanham como alegações falsas surgem, mudam e se espalham. Pode ajudar a reconstruir a trajetória de um boato científico e a comparar suas versões com evidências disponíveis.",
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=243272&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    referenceTitle: "Grupo da Unicamp investiga fake news sobre coronavírus",
    referenceUrl: "https://unicamp.br/unicamp/noticias/2020/03/19/grupo-da-unicamp-investiga-fake-news-sobre-coronavirus",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "unicamp-luiz-carlos-dias",
    universityId: "unicamp",
    name: "Luiz Carlos Dias",
    title: "Professor titular",
    department: "Instituto de Química",
    area: "Química medicinal e evidência em saúde",
    specialties: ["fake news em saúde", "vacinas", "medicamentos", "covid-19", "evidência científica"],
    summary: "Químico medicinal com atuação pública na checagem de alegações sobre vacinas, medicamentos e covid-19. Pode avaliar plausibilidade química, qualidade de estudos e promessas de tratamentos sem comprovação.",
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=245755&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    referenceTitle: "Portal Unicamp inicia faixa de combate às fake news",
    referenceUrl: "https://www2.unicamp.br/unicamp/noticias/2021/01/22/portal-unicamp-inicia-faixa-de-combate-fake-news/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "unicamp-raquel-stucchi",
    universityId: "unicamp",
    name: "Raquel Silveira Bello Stucchi",
    title: "Professora associada",
    department: "Faculdade de Ciências Médicas",
    area: "Infectologia e vacinas",
    specialties: ["desinformação em saúde", "vacinas", "infectologia", "movimento antivacina", "covid-19"],
    summary: "Infectologista com experiência clínica e pública no enfrentamento ao movimento antivacina. Pode checar alegações sobre segurança, eficácia, eventos adversos e recomendações de vacinação.",
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=84051&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    referenceTitle: "Portal Unicamp inicia faixa de combate às fake news",
    referenceUrl: "https://www2.unicamp.br/unicamp/noticias/2021/01/22/portal-unicamp-inicia-faixa-de-combate-fake-news/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "unicamp-maria-luiza-moretti",
    universityId: "unicamp",
    name: "Maria Luiza Moretti",
    title: "Professora titular",
    department: "Faculdade de Ciências Médicas",
    area: "Doenças infecciosas e saúde pública",
    specialties: ["fake news em saúde", "doenças infecciosas", "vacinas", "epidemiologia clínica", "pandemias"],
    summary: "Infectologista com experiência em doenças emergentes, vacinas e resposta a pandemias. Pode confrontar afirmações sobre transmissão, risco, prevenção e tratamento com o consenso e os dados clínicos disponíveis.",
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=53520&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    referenceTitle: "Portal Unicamp inicia faixa de combate às fake news",
    referenceUrl: "https://www2.unicamp.br/unicamp/noticias/2021/01/22/portal-unicamp-inicia-faixa-de-combate-fake-news/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "unicamp-peter-schulz",
    universityId: "unicamp",
    name: "Peter Alexander Bleinroth Schulz",
    title: "Professor titular",
    department: "Faculdade de Ciências Aplicadas",
    area: "Divulgação científica e pensamento crítico",
    specialties: ["negacionismo", "divulgação científica", "pensamento crítico", "evidência", "comunicação da ciência"],
    summary: "Físico e divulgador científico que escreve sobre negacionismo, confiança na ciência e pensamento crítico. Pode ajudar a avaliar se uma alegação representa o estado do conhecimento ou explora incertezas para fabricar dúvida.",
    profileUrl: "https://www2.fca.unicamp.br/profissional/peter-alexander-bleinroth-schulz/",
    sourceLabel: "Faculdade de Ciências Aplicadas da Unicamp",
    referenceTitle: "Ciência, esta jovem aventureira",
    referenceUrl: "https://jornal.unicamp.br/edicao/736/ciencia-esta-jovem-aventureira/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "unicamp-marcelo-buzato",
    universityId: "unicamp",
    name: "Marcelo El Khouri Buzato",
    title: "Professor titular",
    department: "Instituto de Estudos da Linguagem",
    area: "Linguagem e desinformação digital",
    specialties: ["fake news no WhatsApp", "análise de discurso", "linguagem digital", "humanidades digitais", "Qualichat"],
    summary: "Linguista que desenvolve métodos para analisar conversas e conteúdos em aplicativos de mensagem. Pode ajudar a identificar padrões discursivos, enquadramentos e circulação de fake news em grandes coleções de mensagens.",
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=293917&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    referenceTitle: "Ferramenta desenvolvida na Unicamp auxilia pesquisas sobre fake news no WhatsApp",
    referenceUrl: "https://unicamp.br/unicamp/noticias/2021/07/26/ferramenta-desenvolvida-na-unicamp-auxilia-em-pesquisas-sobre-fake-news-no",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "unicamp-claudia-wanderley",
    universityId: "unicamp",
    name: "Claudia Marinho Wanderley",
    title: "Pesquisadora",
    department: "Centro de Lógica, Epistemologia e História da Ciência",
    area: "Educação midiática e desinformação",
    specialties: ["educação midiática", "avaliação de fontes", "desinformação", "direito à informação", "letramento em mídia"],
    summary: "Pesquisadora e uma das coordenadoras do Observatório da Desinformação da Unicamp. Pode ajudar a avaliar fontes, explicar como narrativas manipuladas ganham força e propor abordagens de educação midiática para comunidades e escolas.",
    profileUrl: "https://www.cocen.unicamp.br/centros-e-nucleos/orgaos-interdisciplinares/id/10/cle",
    sourceLabel: "Coordenadoria de Centros e Núcleos da Unicamp",
    referenceTitle: "Projetos de educação midiática atuam no enfrentamento à desinformação",
    referenceUrl: "https://jornal.unicamp.br/noticias/2026/03/18/projetos-de-educacao-midiatica-atuam-no-enfrentamento-a-desinformacao/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "unicamp-anderson-rocha",
    universityId: "unicamp",
    name: "Anderson de Rezende Rocha",
    title: "Professor titular",
    department: "Instituto de Computação",
    area: "Inteligência artificial e forense digital",
    specialties: ["deepfakes", "forense digital", "autenticidade de mídia", "inteligência artificial", "detecção de manipulação"],
    summary: "Cientista da computação especializado em forense digital e detecção de mídia sintética. Pode examinar limites e sinais técnicos de deepfakes, inclusive quando o método de geração ainda não era conhecido pelo detector.",
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=295692&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    referenceTitle: "IA detecta deepfakes criados com técnicas desconhecidas",
    referenceUrl: "https://jornal.unicamp.br/edicao/745/ia-detecta-deepfakes-criados-com-tecnicas-desconhecidas/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "unicamp-anna-christina-bentes",
    universityId: "unicamp",
    name: "Anna Christina Bentes da Silva",
    title: "Professora titular",
    department: "Instituto de Estudos da Linguagem",
    area: "Linguística textual e fake news",
    specialties: ["fake news", "análise textual", "desinformação em saúde", "discurso", "legitimidade de fontes"],
    summary: "Linguista que analisa como textos falsos constroem coerência, autoridade e aparência de legitimidade. Pode ajudar a desmontar escolhas linguísticas de conteúdos enganosos, especialmente em alegações de saúde com potencial de dano.",
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=283012&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    referenceTitle: "Mentiras que matam",
    referenceUrl: "https://jornal.unicamp.br/edicao/721/mentiras-que-matam/",
    verifiedAt: VERIFIED_AT,
  }),

  expert({
    id: "usp-pablo-ortellado",
    universityId: "usp",
    name: "Pablo Ortellado",
    title: "Professor",
    department: "Escola de Artes, Ciências e Humanidades",
    area: "Políticas públicas e ambiente digital",
    specialties: ["desinformação política", "polarização", "plataformas digitais", "regulação", "acesso à informação"],
    summary: "Pesquisador de políticas públicas que monitora polarização, circulação de informação e plataformas digitais. Pode contextualizar campanhas de desinformação política, bolhas e propostas de regulação sem reduzir o problema a uma peça isolada.",
    profileUrl: "https://www.iea.usp.br/pessoas/pasta-pessoap/pablo-ortellado",
    sourceLabel: "Instituto de Estudos Avançados da USP",
    referenceTitle: "Professores da USP dão orientações contra as fake news",
    referenceUrl: "https://jornal.usp.br/atualidades/projeto-de-lei-das-fake-news-encontra-dificuldades-para-enquadrar-whatsapp/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "usp-rodrigo-ratier",
    universityId: "usp",
    name: "Rodrigo Pelegrini Ratier",
    title: "Professor",
    department: "Departamento de Jornalismo e Editoração",
    area: "Jornalismo e educação midiática",
    specialties: ["checagem de vídeos", "deepfakes", "educação midiática", "fake news", "jornalismo"],
    summary: "Jornalista e educador, cofundador do curso Vaza, Falsiane, voltado ao combate à desinformação. Pode orientar a verificação de vídeos, áudios e peças sensacionalistas e traduzir técnicas de checagem para o público não especializado.",
    profileUrl: "https://repositorio.usp.br/item/003206369",
    sourceLabel: "Repositório da Produção USP",
    referenceTitle: "Como identificar e combater as fake news no Brasil?",
    referenceUrl: "https://jornal.usp.br/atualidades/como-identificar-e-combater-as-fake-news-no-brasil/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "usp-christian-dunker",
    universityId: "usp",
    name: "Christian Ingo Lenz Dunker",
    title: "Professor titular",
    department: "Instituto de Psicologia",
    area: "Psicanálise, crença e desinformação",
    specialties: ["fake news", "confiança", "afetos", "teorias da conspiração", "bolhas de consenso"],
    summary: "Psicanalista que analisa confiança, afetos, bolhas de consenso e teorias da conspiração. Pode explicar por que ódio, medo e identificação com grupos favorecem o compartilhamento e como desenvolver um ceticismo saudável.",
    profileUrl: "https://www.ip.usp.br/site/christian-ingo-lenz-dunker/",
    sourceLabel: "Instituto de Psicologia da USP",
    referenceTitle: "Como identificar e combater as fake news no Brasil?",
    referenceUrl: "https://jornal.usp.br/atualidades/como-identificar-e-combater-as-fake-news-no-brasil/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "usp-eugenio-bucci",
    universityId: "usp",
    name: "Eugênio Bucci",
    title: "Professor titular",
    department: "Escola de Comunicações e Artes",
    area: "Ética jornalística e verdade factual",
    specialties: ["verdade factual", "fake news", "ética jornalística", "comunicação pública", "democracia"],
    summary: "Jornalista e pesquisador de ética, imprensa e cultura democrática. Pode ajudar a distinguir notícia de propaganda fraudulenta, discutir padrões de verificação e situar o papel do jornalismo profissional no combate à desinformação.",
    profileUrl: "https://www.iea.usp.br/pesquisa/pessoas/pasta-pessoae/eugenio-bucci",
    sourceLabel: "Instituto de Estudos Avançados da USP",
    referenceTitle: "Somente o jornalismo profissional pode combater as fake news",
    referenceUrl: "https://jornal.usp.br/atualidades/somente-o-jornalismo-profissional-pode-combater-as-fake-news/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "usp-luciano-maluly",
    universityId: "usp",
    name: "Luciano Victor Barros Maluly",
    title: "Professor",
    department: "Departamento de Jornalismo e Editoração",
    area: "Jornalismo e combate às fake news",
    specialties: ["fake news", "educação jornalística", "radiojornalismo", "checagem", "cidadania"],
    summary: "Jornalista e criador da série ECA-USP Contra as Fake News, concebida para levar práticas de identificação de desinformação ao público. Pode discutir formatos de educação jornalística e estratégias de comunicação para prevenção.",
    profileUrl: "https://celacc.eca.usp.br/pt-br/pesquisadores/detalhes/1998",
    sourceLabel: "Centro de Estudos Latino-Americanos sobre Comunicação e Cultura da USP",
    referenceTitle: "Professores da USP dão orientações contra as fake news",
    referenceUrl: "https://jornal.usp.br/atualidades/projeto-de-lei-das-fake-news-encontra-dificuldades-para-enquadrar-whatsapp/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "usp-marcio-moretto",
    universityId: "usp",
    name: "Marcio Moretto Ribeiro",
    title: "Professor",
    department: "Escola de Artes, Ciências e Humanidades",
    area: "Redes de desinformação política",
    specialties: ["redes de desinformação", "polarização", "análise de dados", "política digital", "mídias sociais"],
    summary: "Pesquisador de sistemas de informação que mapeia redes políticas e fluxos de conteúdo em mídias sociais. Pode ajudar a identificar comunidades, conexões e padrões coordenados por trás de campanhas de desinformação.",
    profileUrl: "https://www5.each.usp.br/docentes/",
    sourceLabel: "Escola de Artes, Ciências e Humanidades da USP",
    referenceTitle: "Armas de desinformação em massa",
    referenceUrl: "https://jornal.usp.br/atualidades/armas-de-desinformacao-em-massa/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "usp-helder-nakaya",
    universityId: "usp",
    name: "Helder I. Nakaya",
    title: "Professor",
    department: "Faculdade de Ciências Farmacêuticas",
    area: "Bioinformática e comunicação científica",
    specialties: ["negacionismo científico", "vacinas", "bioinformática", "consenso científico", "saúde pública"],
    summary: "Pesquisador de bioinformática e imunologia que atua na comunicação pública de evidências sobre doenças e vacinas. Pode checar afirmações biomédicas e explicar a diferença entre um estudo isolado e o conjunto do conhecimento científico.",
    profileUrl: "https://www.iea.usp.br/pessoas/pasta-pessoah/helder-nakaya",
    sourceLabel: "Instituto de Estudos Avançados da USP",
    referenceTitle: "A ciência contra o negacionismo",
    referenceUrl: "https://jornal.usp.br/ciencias/a-ciencia-contra-o-negacionismo/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "usp-alicia-kowaltowski",
    universityId: "usp",
    name: "Alicia Juliana Kowaltowski",
    title: "Professora titular",
    department: "Instituto de Química",
    area: "Bioquímica e comunicação científica",
    specialties: ["negacionismo", "evidência científica", "bioquímica", "comunicação da ciência", "saúde"],
    summary: "Bioquímica e divulgadora científica que debate negacionismo e qualidade da evidência. Pode avaliar alegações sobre metabolismo e saúde e explicar como incerteza, revisão por pares e consenso funcionam na ciência.",
    profileUrl: "https://www.iq.usp.br/portaliqusp/?q=pt-br%2Fusers%2Falicia-juliana-kowaltowski",
    sourceLabel: "Instituto de Química da USP",
    referenceTitle: "A ciência contra o negacionismo",
    referenceUrl: "https://jornal.usp.br/ciencias/a-ciencia-contra-o-negacionismo/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "usp-esper-kallas",
    universityId: "usp",
    name: "Esper Georges Kallás",
    title: "Professor titular",
    department: "Faculdade de Medicina",
    area: "Infectologia, vacinas e desinformação em saúde",
    specialties: ["fake news em saúde", "vacinas", "infectologia", "ensaios clínicos", "pandemias"],
    summary: "Infectologista com atuação em ensaios clínicos, vacinas e resposta à covid-19. Pode verificar alegações sobre doenças infecciosas e separar hipóteses, resultados preliminares e recomendações sustentadas por evidência.",
    profileUrl: "https://www.iea.usp.br/pessoas/pasta-pessoae/esper-kallas",
    sourceLabel: "Instituto de Estudos Avançados da USP",
    referenceTitle: "O papel das universidades no combate à desinformação",
    referenceUrl: "https://jornal.usp.br/atualidades/o-papel-das-universidades-no-combate-a-desinformacao/",
    verifiedAt: VERIFIED_AT,
  }),
  expert({
    id: "usp-fabio-cozman",
    universityId: "usp",
    name: "Fábio Gagliardi Cozman",
    title: "Professor titular",
    department: "Escola Politécnica",
    area: "Inteligência artificial e conteúdo sintético",
    specialties: ["inteligência artificial", "desinformação sintética", "deepfakes", "alucinações de IA", "incerteza"],
    summary: "Especialista em inteligência artificial e decisão sob incerteza. Pode explicar como modelos generativos fabricam textos, imagens e vídeos convincentes, quais são os limites dos detectores e como avaliar respostas produzidas por IA.",
    profileUrl: "https://www.iea.usp.br/pessoas/pasta-pessoaf/fabio-gagliardi-cozman",
    sourceLabel: "Instituto de Estudos Avançados da USP",
    referenceTitle: "Inteligências artificiais entram em campo contra e a favor da desinformação",
    referenceUrl: "https://jornal.usp.br/atualidades/inteligencias-artificiais-entram-em-campo-contra-e-a-favor-da-desinformacao/",
    verifiedAt: VERIFIED_AT,
  }),
];

export const seedCurators: Curator[] = [
  ["pedro@cointeligencia.ai", "Pedro Burgos"],
  ["aoigor@gmail.com", "Igor"],
  ["fegiacomassi@gmail.com", "Fernanda"],
  ["marinatmac@gmail.com", "Marina"],
  ["lidia.sousa@gmail.com", "Lidia"],
  ["francisco.belda@projor.org.br", "Francisco Belda"],
].map(([email, name]) => ({ email, name, active: true, createdAt: SEEDED_AT }));
