import type { Curator, Expert, University } from "@/lib/types";

const SEEDED_AT = "2026-08-17T12:00:00.000Z";
const VERIFIED_AT = "2026-08-17";

export const seedUniversities: University[] = [
  {
    id: "ufmg",
    name: "Universidade Federal de Minas Gerais",
    acronym: "UFMG",
    state: "MG",
    directoryUrl: "https://somos.ufmg.br/",
    directoryLabel: "Somos UFMG",
    notes: "Diretório institucional central e pesquisável, com perfis e produção acadêmica.",
    isActive: true,
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
  },
  {
    id: "unicamp",
    name: "Universidade Estadual de Campinas",
    acronym: "Unicamp",
    state: "SP",
    directoryUrl: "https://portal.dados.unicamp.br/",
    directoryLabel: "Portal Dados Unicamp",
    notes: "Portal institucional central com busca por docentes, temas, unidades e programas.",
    isActive: true,
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
  },
  {
    id: "usp",
    name: "Universidade de São Paulo",
    acronym: "USP",
    state: "SP",
    directoryUrl: "https://www5.usp.br/keywords-s/pesquisadores-usp/",
    directoryLabel: "Pesquisadores USP e diretórios das unidades",
    notes: "Perfis públicos oficiais distribuídos entre portais de unidades, institutos e serviços USP.",
    isActive: true,
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
  },
];

type SeedExpert = Omit<Expert, "universityName" | "universityAcronym">;

export const seedExperts: SeedExpert[] = [
  {
    id: "ufmg-evandro-cunha",
    universityId: "ufmg",
    name: "Evandro Landulfo Teixeira Paradela Cunha",
    title: "Professor",
    department: "Faculdade de Letras",
    area: "Linguística computacional",
    specialties: ["processamento de linguagem natural", "desinformação", "fake news", "extremismo online", "linguística forense"],
    summary: "Pesquisa linguagem em ambientes digitais, incluindo identificação de desinformação e análise computacional de discursos online.",
    email: null,
    phone: null,
    profileUrl: "https://somos.ufmg.br/professor/evandro-landulfo-teixeira-paradela-cunha",
    sourceLabel: "Somos UFMG",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "ufmg-andre-mintz",
    universityId: "ufmg",
    name: "André Goes Mintz",
    title: "Professor",
    department: "Departamento de Comunicação Social",
    area: "Comunicação e métodos digitais",
    specialties: ["inteligência artificial", "estudos de plataforma", "métodos digitais", "racismo algorítmico", "visualização de dados"],
    summary: "Atua na interseção entre comunicação, plataformas digitais, métodos computacionais e questões sociais ligadas a algoritmos.",
    email: null,
    phone: null,
    profileUrl: "https://somos.ufmg.br/professor/andre-goes-mintz",
    sourceLabel: "Somos UFMG",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "ufmg-carlos-dandrea",
    universityId: "ufmg",
    name: "Carlos Frederico de Brito D'Andréa",
    title: "Professor",
    department: "Departamento de Comunicação Social",
    area: "Comunicação digital",
    specialties: ["plataformas digitais", "mídias sociais", "desinformação", "desordem informacional", "métodos digitais"],
    summary: "Pesquisa controvérsias, desinformação e dinâmicas de circulação de informação em plataformas e mídias sociais.",
    email: null,
    phone: null,
    profileUrl: "https://somos.ufmg.br/professor/Carlos-Frederico-de-Brito-D-Andrea",
    sourceLabel: "Somos UFMG",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "ufmg-deborah-malta",
    universityId: "ufmg",
    name: "Deborah Carvalho Malta",
    title: "Professora",
    department: "Escola de Enfermagem",
    area: "Saúde pública e epidemiologia",
    specialties: ["doenças crônicas", "epidemiologia", "vigilância em saúde", "inquéritos populacionais", "políticas de saúde"],
    summary: "Especialista em vigilância de doenças crônicas, epidemiologia e avaliação de políticas e indicadores de saúde pública.",
    email: null,
    phone: null,
    profileUrl: "https://somos.ufmg.br/professor/deborah-carvalho-malta",
    sourceLabel: "Somos UFMG",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "ufmg-wagner-meira",
    universityId: "ufmg",
    name: "Wagner Meira Junior",
    title: "Professor titular",
    department: "Departamento de Ciência da Computação",
    area: "Ciência de dados e inteligência artificial",
    specialties: ["mineração de dados", "aprendizado de máquina", "redes sociais", "cibersegurança", "transparência algorítmica"],
    summary: "Pesquisa sistemas de grande escala, mineração de dados, inteligência artificial e impactos sociais de algoritmos.",
    email: null,
    phone: null,
    profileUrl: "https://somos.ufmg.br/professor/wagner-meira-junior",
    sourceLabel: "Somos UFMG",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "unicamp-anderson-rocha",
    universityId: "unicamp",
    name: "Anderson de Rezende Rocha",
    title: "Professor titular",
    department: "Instituto de Computação",
    area: "Inteligência artificial e forense digital",
    specialties: ["inteligência artificial", "forense digital", "aprendizado de máquina", "dados complexos", "autenticidade de mídia"],
    summary: "Pesquisa inteligência artificial e forense digital, com aplicações na detecção de manipulação e análise de dados complexos.",
    email: "arrocha@unicamp.br",
    phone: null,
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=295692&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "unicamp-germana-barata",
    universityId: "unicamp",
    name: "Germana Fernandes Barata",
    title: "Pesquisadora",
    department: "Laboratório de Estudos Avançados em Jornalismo",
    area: "Divulgação científica",
    specialties: ["jornalismo científico", "comunicação pública da ciência", "divulgação científica", "percepção pública da ciência"],
    summary: "Pesquisa comunicação pública da ciência e jornalismo científico, com foco em circulação e percepção social do conhecimento.",
    email: "germana@unicamp.br",
    phone: null,
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=284885&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "unicamp-jurandir-zullo",
    universityId: "unicamp",
    name: "Jurandir Zullo Junior",
    title: "Pesquisador",
    department: "Centro de Pesquisas Meteorológicas e Climáticas Aplicadas à Agricultura",
    area: "Clima e agrometeorologia",
    specialties: ["mudanças climáticas", "meteorologia", "agrometeorologia", "sensoriamento remoto", "agricultura"],
    summary: "Atua com clima, sensoriamento remoto e impactos meteorológicos sobre agricultura e uso do território.",
    email: "jurandir@unicamp.br",
    phone: null,
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=88064&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "unicamp-paulo-jannuzzi",
    universityId: "unicamp",
    name: "Paulo de Martino Jannuzzi",
    title: "Pesquisador colaborador",
    department: "Núcleo de Estudos de Políticas Públicas",
    area: "Políticas públicas e indicadores sociais",
    specialties: ["avaliação de políticas públicas", "indicadores sociais", "estatísticas públicas", "planejamento governamental"],
    summary: "Especialista em indicadores sociais, sistemas de informação e avaliação de programas e políticas públicas.",
    email: "paulomj@unicamp.br",
    phone: null,
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=318450&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "unicamp-rafael-evangelista",
    universityId: "unicamp",
    name: "Rafael de Almeida Evangelista",
    title: "Pesquisador",
    department: "Laboratório de Estudos Avançados em Jornalismo",
    area: "Tecnologia, política e sociedade",
    specialties: ["governança de plataformas", "vigilância", "dados pessoais", "política da tecnologia", "jornalismo"],
    summary: "Pesquisa implicações políticas e sociais de plataformas, dados, vigilância e infraestrutura digital.",
    email: "rae@unicamp.br",
    phone: null,
    profileUrl: "https://portal.dados.unicamp.br/perfil?origem=&docente=284466&sigla_unidade=&nome_unidade=&nome_programa=",
    sourceLabel: "Portal Dados Unicamp",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "usp-pablo-ortellado",
    universityId: "usp",
    name: "Pablo Ortellado",
    title: "Professor",
    department: "Escola de Artes, Ciências e Humanidades",
    area: "Políticas públicas e ambiente digital",
    specialties: ["desinformação", "polarização política", "plataformas digitais", "regulação de inteligência artificial", "acesso à informação"],
    summary: "Pesquisa circulação de informação, polarização e políticas para plataformas digitais e inteligência artificial.",
    email: "paort@usp.br",
    phone: null,
    profileUrl: "https://www.iea.usp.br/pessoas/pasta-pessoap/pablo-ortellado",
    sourceLabel: "Instituto de Estudos Avançados da USP",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "usp-paulo-artaxo",
    universityId: "usp",
    name: "Paulo Artaxo",
    title: "Professor sênior",
    department: "Instituto de Física",
    area: "Física atmosférica e clima",
    specialties: ["mudanças climáticas", "Amazônia", "aerossóis atmosféricos", "poluição do ar", "emissões"],
    summary: "Especialista em mudanças climáticas, Amazônia, partículas atmosféricas e impactos de emissões sobre clima e saúde.",
    email: "artaxo@if.usp.br",
    phone: null,
    profileUrl: "https://portal.if.usp.br/ifusp/pt-br/users/artaxo",
    sourceLabel: "Instituto de Física da USP",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "usp-fabio-cozman",
    universityId: "usp",
    name: "Fábio Gagliardi Cozman",
    title: "Professor titular",
    department: "Escola Politécnica",
    area: "Inteligência artificial",
    specialties: ["aprendizado de máquina", "incerteza", "tomada de decisão", "inteligência artificial", "IA responsável"],
    summary: "Pesquisa inteligência artificial, aprendizado de máquina e tomada de decisão sob incerteza; dirige o Center for Artificial Intelligence.",
    email: "fgcozman@usp.br",
    phone: null,
    profileUrl: "https://www.iea.usp.br/pessoas/pasta-pessoaf/fabio-gagliardi-cozman",
    sourceLabel: "Instituto de Estudos Avançados da USP",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "usp-deisy-ventura",
    universityId: "usp",
    name: "Deisy Ventura",
    title: "Professora titular",
    department: "Faculdade de Saúde Pública",
    area: "Saúde global e direitos humanos",
    specialties: ["pandemias", "emergências sanitárias", "saúde global", "direitos humanos", "migração"],
    summary: "Pesquisa governança de emergências sanitárias, ética em saúde global, direitos humanos e mobilidade humana.",
    email: null,
    phone: null,
    profileUrl: "https://www.iea.usp.br/pessoas/pasta-pessoad/deisy-ventura",
    sourceLabel: "Instituto de Estudos Avançados da USP",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
  {
    id: "usp-wilson-bueno",
    universityId: "usp",
    name: "Wilson da Costa Bueno",
    title: "Professor sênior",
    department: "Escola de Comunicações e Artes",
    area: "Jornalismo e comunicação científica",
    specialties: ["jornalismo especializado", "divulgação científica", "comunicação ambiental", "comunicação em saúde"],
    summary: "Atua em jornalismo científico e especializado, comunicação organizacional e divulgação de temas ambientais e de saúde.",
    email: null,
    phone: null,
    profileUrl: "https://portalservicos.usp.br/especialistas/especialistaObter?codpub=97A29E6FE1D9",
    sourceLabel: "Portal de Especialistas da USP",
    verifiedAt: VERIFIED_AT,
    status: "published",
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    updatedBy: "base-inicial",
  },
];

export const seedCurators: Curator[] = [
  ["pedro@cointeligencia.ai", "Pedro Burgos"],
  ["aoigor@gmail.com", "Igor"],
  ["fegiacomassi@gmail.com", "Fernanda"],
  ["marinatmac@gmail.com", "Marina"],
  ["lidia.sousa@gmail.com", "Lidia"],
  ["francisco.belda@projor.org.br", "Francisco Belda"],
].map(([email, name]) => ({ email, name, active: true, createdAt: SEEDED_AT }));
